# Site wide configuration

title: Deployd documentation
description: "Documentation for Deployd"
logo: deployd-logo.png
teaser: 400x250.gif
locale: en_US
url: //nicolasritouet.github.io/documentation

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Nicolas Ritouet
  web: http://www.deployd.com
  email: nicolas@ritouet.com
  twitter: deploydapp
  bio: "Deployd is a tool to design, build, and scale APIs for web and mobile apps in minutes instead of days."
  avatar: deployd-logo.png # 160x160 px image for author byline
  google:
    plus: +deployd
    ad-client: ca-pub-1234567
    ad-slot: 1234567
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
